// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfuvjfraxciAcVenxJLZ9Gx1LfChB-mzM',
    appId: '1:845859826050:web:f4122e9bd403bb1da5079b',
    messagingSenderId: '845859826050',
    projectId: 'avd-exam',
    authDomain: 'avd-exam.firebaseapp.com',
    storageBucket: 'avd-exam.firebasestorage.app',
    measurementId: 'G-48KFEEYGLZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABCPM3g9__qVLPO87XhMmybIUOukjZAYM',
    appId: '1:845859826050:android:34203ef6503dfcc9a5079b',
    messagingSenderId: '845859826050',
    projectId: 'avd-exam',
    storageBucket: 'avd-exam.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnbC1T2cHwq1YkBuPVLqtIB-RI-4aot-c',
    appId: '1:845859826050:ios:98ac0b25478ad89aa5079b',
    messagingSenderId: '845859826050',
    projectId: 'avd-exam',
    storageBucket: 'avd-exam.firebasestorage.app',
    iosBundleId: 'com.example.avd2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnbC1T2cHwq1YkBuPVLqtIB-RI-4aot-c',
    appId: '1:845859826050:ios:98ac0b25478ad89aa5079b',
    messagingSenderId: '845859826050',
    projectId: 'avd-exam',
    storageBucket: 'avd-exam.firebasestorage.app',
    iosBundleId: 'com.example.avd2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfuvjfraxciAcVenxJLZ9Gx1LfChB-mzM',
    appId: '1:845859826050:web:af39b2f558f06a5ba5079b',
    messagingSenderId: '845859826050',
    projectId: 'avd-exam',
    authDomain: 'avd-exam.firebaseapp.com',
    storageBucket: 'avd-exam.firebasestorage.app',
    measurementId: 'G-RYR9H9ZYLD',
  );
}
